name: CI setup for Go

on:
  push:
    branches: [master]
    
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        echo Hello there!
  
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.16.2
        # Whether to download only stable versions
        stable: true
        # Used to pull node distributions from go-versions.  Since there's a default, this is typically not supplied by the user.
        token: ${{ github.token }}
        
    - name: Check go version
      run: |
        go version

    - name: Checkout
      uses: action/checkout@v2
      
